SELECT 
    season,
    round,
    url AS race_url,
    raceName,
    Circuit_circuitId,
    Circuit_url AS circuit_url,
    Circuit_circuitName,
    Circuit_Location_lat,
    Circuit_Location_long,
    Circuit_Location_locality,
    Circuit_Location_country,
    date AS race_date,
    time AS race_time,
    QualifyingResults_number AS car_number,
    QualifyingResults_position AS position,
    QualifyingResults_Driver_driverId AS driver_id,
    QualifyingResults_Driver_permanentNumber AS permanent_number,
    QualifyingResults_Driver_code AS driver_code,
    QualifyingResults_Driver_url AS driver_url,
    QualifyingResults_Driver_givenName AS driver_given_name,
    QualifyingResults_Driver_familyName AS driver_family_name,
    QualifyingResults_Driver_dateOfBirth AS driver_dob,
    QualifyingResults_Driver_nationality AS driver_nationality,
    QualifyingResults_Constructor_constructorId AS constructor_id,
    QualifyingResults_Constructor_url AS constructor_url,
    QualifyingResults_Constructor_name AS constructor_name,
    QualifyingResults_Constructor_nationality AS constructor_nationality,
    QualifyingResults_Q1 AS q1_time,
    QualifyingResults_Q2 AS q2_time,
    QualifyingResults_Q3 AS q3_time
FROM {{source('f1_ingested', 'qualifying')}}
